src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $title = null;

    
    #[ORM\Column(length: 100, nullable: true)]
    private ?string $product_id = null;

    #[ORM\Column(length: 100)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getProduct(): ?int
    {
        return $this->product_id;
    }

    public function setProduct(string $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Entity/ShopCart.php
<?php

namespace App\Entity;

use App\Repository\ShopCartRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShopCartRepository::class)]
class ShopCart
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\ManyToOne(inversedBy: 'shopCarts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product_id = null;

    #[ORM\ManyToOne(inversedBy: 'shopCartss')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getProductId(): ?Product
    {
        return $this->product_id;
    }

    public function setProductId(?Product $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }
}

src/Form/ShopCartType.php
<?php

namespace App\Form;

use App\Entity\ShopCart;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ShopCartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantity', NumberType::class,['empty_data'=> '1'])
            #->add('product_id')
            #->add('user_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ShopCart::class,
        ]);
    }
}

src/Controller/ShopCartController.php
<?php

namespace App\Controller;

use id;
use DateTime;
use App\Entity\ShopCard;
use App\Form\ShopCartType;
use App\Repository\ShopCardRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/shop/cart')]
class ShopCartController extends AbstractController
{
    #[Route('/', name: 'app_shop_cart_index', methods: ['GET'])]
    public function index(ShopCardRepository $shopCardRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        $shop_carts = $shopCardRepository->findBy(['user' => $user->getId()]);

        return $this->render('shop_cart/shopcard.html.twig', [
            'shop_carts' =>  $shop_carts,
        ]);
    }
    #[Route('/order', name: 'app_shop_cart_order', methods:['GET'])]
    public function order(ShopCardRepository $shopCardRepository): Response
    {
        
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        $shop_carts = $shopCardRepository->findBy(['user' => $user->getId()]);
        return $this->render('shop_cart/payment.html.twig', [
            'shop_carts' =>  $shop_carts,
        ]);
    }
    #[Route('/complete', name: 'app_shop_cart_complete', methods:['GET', 'POST'])]
    public function complete(ManagerRegistry $doctrine, ShopCardRepository $shopCardRepository,  Request $request): Response
    {
        #kullanıcı bilgileri
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        $shop_carts = $shopCardRepository->findBy(['user' => $user->getId()]);
        #ürün bilgileri
        $entityManager = $doctrine->getManager();
        $conn = $doctrine->getManager()->getConnection();
        $sql = '
            INSERT INTO `order` (user_id, `name`, email, address, phone,total, status, ip)
            VALUES(:user_id, :name, :email, :address, :phone, :total, :status, :ip)
        ';
        $stmt = $conn->prepare($sql);
        
        $stmt->executeQuery([
            'user_id' => $user->getId(),
            'name' => $request->get('name'),
            'email' => $request->get('email'),
            'address' => $request->get('address'),
            'phone' => $request->get('phone'),
            'total' => $request->get('total'),
            'status' => 'New',
            'ip' => $_SERVER['REMOTE_ADDR'],

        ]);
        

        $orderid=$entityManager->getConnection()->lastInsertId();
        foreach($shop_carts as $rs){
            $sql = '
            INSERT INTO `order_product` (user_id, product_id, orders_id, price, quantity,total)
            VALUES(:user_id, :product_id, :orders_id, :price, :quantity, :total)
        ';
        $stmt = $conn->prepare($sql);
        
        $stmt->executeQuery([
            'user_id' => $user->getId(),
            'product_id' => $rs->getProduct()->getId(),
            'orders_id' => $orderid,
            'price' => $rs->getProduct()->getPrice(),
            'quantity' => $rs->getQuantity(),
            'total' => $rs->getQuantity()*$rs->getProduct()->getPrice()

        ]);
    }
        $sql ='DELETE FROM shop_card WHERE user_id='.$user->getId();
        $stmt = $conn->prepare($sql);
        $stmt->executeQuery();



        return $this->render('shop_cart/complete.html.twig', [
            'shop_carts' =>  $shop_carts,
        ]);
    }


    #[Route('/new', name: 'app_shop_cart_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ShopCardRepository $shopCardRepository): Response
    {
        $shopCard = new ShopCard();
        $form = $this->createForm(ShopCartType::class, $shopCard);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $shopCardRepository->add($shopCard, true);

            return $this->redirectToRoute('app_shop_cart_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('shop_cart/new.html.twig', [
            'shop_cart' => $shopCard,
            'form' => $form,
        ]);
    }


    #[Route('/add', name: 'app_shop_cart_add', methods: ['GET', 'POST'])]
    public function update(Request $request, ManagerRegistry $doctrine): Response
    {
        $entityManager = $doctrine->getManager();
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();

        $conn = $doctrine->getManager()->getConnection();
        $sql = '
            INSERT INTO shop_card (quantity, product_id, user_id)
            VALUES(:quantity, :product_id,:user_id)
        ';
        $stmt = $conn->prepare($sql);
        $stmt->executeQuery([
            'quantity' => $request->get('quantity'),
            'product_id' => $request->get('product_id'),
            'user_id' => $user->getId()
        ]);

        $this->addFlash(
            'success',
            'Ürün başarılı eklendi'
        );
        $route = $request->headers->get('referer');
        return $this->redirect($route);
    }



    #[Route('/{id}', name: 'app_shop_cart_show', methods: ['GET'])]
    public function show(ShopCard $shopCard): Response
    {
        return $this->render('shop_cart/show.html.twig', [
            'shop_cart' => $shopCard,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_shop_cart_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ShopCard $shopCard, ShopCardRepository $shopCardRepository): Response
    {
        $form = $this->createForm(ShopCartType::class, $shopCard);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $shopCardRepository->add($shopCard, true);

            return $this->redirectToRoute('app_shop_cart_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('shop_cart/edit.html.twig', [
            'shop_cart' => $shopCard,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_shop_cart_delete', methods: ['POST'])]
    public function delete(Request $request, ShopCard $shopCard, ShopCardRepository $shopCardRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $shopCard->getId(), $request->request->get('_token'))) {
            $shopCardRepository->remove($shopCard, true);
        }

        return $this->redirectToRoute('app_shop_cart_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/shop_cart/_delete_form.html.twig
<form method="post" action="{{ path('app_shop_cart_delete', {'id': shop_cart.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ shop_cart.id) }}">
    <button class="btn">Delete</button>
</form>

templates/shop_cart/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/shop_cart/complete.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}Order complete
{% endblock %}

{% block sidebar %}
	{% include 'home/sidebar.html.twig' %}
{% endblock %}
{% block content %}
	<!-- Contact Start -->
	<div class="container-fluid pt-5">
		<div class="text-center mb-4">
			<h2 class="section-title px-5">
				<span class="px-2">Satın Alma İşlemi Başarıyla Tamamlandı</span>
				
			</h2><br>
			Kitabınız En Kısa Sürede Teslim Edilecektir
		</div>
		<div class="row px-xl-5">
			<div class="col-lg-8 mb-5">
				<div class="contact-form">
					<div id="success"></div>

				</div>
			</div>
			<!-- Contact End -->

		{% endblock %}

templates/shop_cart/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ShopCart{% endblock %}

{% block body %}
    <h1>Edit ShopCart</h1>

    {{ include('shop_cart/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_shop_cart_index') }}">back to list</a>

    {{ include('shop_cart/_delete_form.html.twig') }}
{% endblock %}

templates/shop_cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ShopCart index{% endblock %}

{% block body %}
    <h1>ShopCart index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for shop_cart in shop_carts %}
            <tr>
                <td>{{ shop_cart.id }}</td>
                <td>{{ shop_cart.quantity }}</td>
                <td>
                    <a href="{{ path('app_shop_cart_show', {'id': shop_cart.id}) }}">show</a>
                    <a href="{{ path('app_shop_cart_edit', {'id': shop_cart.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_shop_cart_new') }}">Create new</a>
{% endblock %}

templates/shop_cart/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ShopCart{% endblock %}

{% block body %}
    <h1>Create new ShopCart</h1>

    {{ include('shop_cart/_form.html.twig') }}

    <a href="{{ path('app_shop_cart_index') }}">back to list</a>
{% endblock %}

templates/shop_cart/payment.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}order
{% endblock %}

{% block sidebar %}
	{% include 'home/sidebar.html.twig' %}
{% endblock %}

{% block content %}
	<!-- Contact Start -->
	<div class="container-fluid pt-5">
		<div class="text-center mb-4">
			<h2 class="section-title px-5">
				<span class="px-2">Shipping Addres</span>
			</h2>
		</div>
		<div class="row px-xl-5">
			<div class="col-lg-7 mb-5">
				<div class="contact-form">
					<div id="success"></div>
					{% for label, messages in app.flashes %}
						{% for message in messages %}
							<div class="alert alert-{{ label }}">
								Mesajınız başıryla gönderildi
							</div>
						{% endfor %}
					{% endfor %}
				</div>
			</div>
			<div class="container-fluid pt-5">
				<form action="{{ path('app_shop_cart_complete') }}" method="post">
					<div class="col-lg-5 mb-5">
						<h5 class="font-weight-semi-bold mb-3">İletişim Bilgileri / Kart Bilgileri</h5>
						<div class="row">
							<div class="col-md-6 form-group">
								<label>Name</label>
								<input class="form-control" name="name" value="{{ app.user.name }}" type="text" placeholder="Name">
							</div>

							<div class="col-md-6 form-group">
								<label>Kart Adı</label>
								<input class="form-control"  name="cardname" type="text" placeholder="Kart Adı">
							</div>
							<div class="col-md-6 form-group">
								<label>E-mail</label>
								<input class="form-control" name="email" value="{{ app.user.email }}" type="email" placeholder="E-mail">
							</div>
							<div class="col-md-6 form-group">
								<label>Kart no</label>
								<input class="form-control" name="cardno" type="text" placeholder="Kart no">
							</div>
							<div class="col-md-6 form-group">
								<label>phone</label>
								<input class="form-control" name="phone" value="{{ app.user.phone }}" type="text" placeholder="phone">
							</div>
							<div class="col-md-6 form-group">
								<label>Son kullanım tarihi</label>
								<input class="form-control" name="carddate"  type="text" placeholder="Son kullanım tarihi">
							</div>
							<div class="col-md-6 form-group">
								<label>Adres</label>
								<input class="form-control" name="address" value="{{ app.user.address }}" type="text" placeholder="address">
							</div>
							<div class="col-md-6 form-group">
								<label>Güvenlik Kodu</label>
								<input class="form-control" name="cardcode" type="text" placeholder="Güvenlik Kodu">
							</div>
                            {% set total =0 %}
                            {% for rs in shop_carts %}
                            {% set total=total + rs.product.price * rs.quantity %}
                            {% endfor %}
							<div class="col-md-6 form-group">
								<label>Total</label>
								<input class="form-control" name="total" value="${{ total }}" type="text" placeholder="Total">
							</div>
							<div class="col-md-6 form-group">
								<input class="form-control btn btn-success" type="submit" placeholder="Sipariş ver">
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Contact End -->{% endblock %}

templates/shop_cart/shopcard.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}Shop Card
{% endblock %}

{% block sidebar %}
	{% include 'home/sidebar.html.twig' %}
{% endblock %}
{% block content %}
	<!-- Contact Start -->
	<div class="container-fluid pt-5">
		<div class="text-center mb-4">
			<h2 class="section-title px-5">
				<span class="px-2">Shop Card</span>
			</h2>
		</div>
		<div class="row px-xl-5">
			<div class="col-lg-8 mb-5">
				<div class="contact-form">
					<div id="success"></div>
					<!-- Cart Start -->
					<div class="container-fluid pt-5">
						<div class="row px-xl-5">
							<div class="col-lg-8 table-responsive mb-5">
								<table class="table table-bordered text-center mb-0">
									<thead class="bg-secondary text-dark">
										<tr>
											<th>Products</th>
											<th>Price</th>
											<th>Quantity</th>
											<th>Total</th>
											<th>Remove</th>
										</tr>
									</thead>
									<tbody class="align-middle">
                                        {% set total=0 %}
										{% for rs in shop_carts %}
											<tr>
												<td class="align-middle"><img src="{{ asset('uploads/images/' ~ rs.product.image) }}" alt="" style="width: 50px;">
													{{ rs.product.title}}t</td>
												<td class="align-middle">${{ rs.product.price * rs.quantity }}</td>
												<td class="align-middle">
													<div class="input-group quantity mx-auto" style="width: 100px;">
														<div class="input-group-btn">
															<button class="btn btn-sm btn-primary btn-minus">
																<i class="fa fa-minus"></i>
															</button>
														</div>
														<input type="text" class="form-control form-control-sm bg-secondary text-center" value="{{ rs.quantity }}">
														<div class="input-group-btn">
															<button class="btn btn-sm btn-primary btn-plus">
																<i class="fa fa-plus"></i>
															</button>
														</div>
													</div>
												</td>
												<td class="align-middle">${{ rs.product.price * rs.quantity }}</td>
												<td class="align-middle">
													<button class="btn btn-sm btn-primary">
														<i class="fa fa-times"></i>
													</button>
												</td>
											</tr>
                                        {% set total=total + rs.product.price * rs.quantity %}
										{% endfor %}
									</tbody>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="col-lg-4">
						
						<div class="card border-secondary mb-5">
							<div class="card-header bg-secondary border-0">
								<h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
							</div>

						</div>
						<div class="card-footer border-secondary bg-transparent">
							<div class="d-flex justify-content-between mt-2">
								<h5 class="font-weight-bold">Total</h5>
								<h5 class="font-weight-bold">${{ total }}</h5>
							</div>
							<a href="{{ path('app_shop_cart_order')}}" class="btn btn-block btn-primary my-3 py-3">Sipariş Ver</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Cart End -->
	</div>
</div>
<!-- Contact End -->{% endblock %}

templates/shop_cart/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ShopCart{% endblock %}

{% block body %}
    <h1>ShopCart</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ shop_cart.id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ shop_cart.quantity }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_shop_cart_index') }}">back to list</a>

    <a href="{{ path('app_shop_cart_edit', {'id': shop_cart.id}) }}">edit</a>

    {{ include('shop_cart/_delete_form.html.twig') }}
{% endblock %}